framework: torch
env: coverage
lambda: 0.9
entropy_coeff: 0.01
kl_coeff: 0.2
kl_target: 0.01
clip_param: 0.2
rollout_fragment_length: 100
train_batch_size: 6400
sgd_minibatch_size: 1600
num_sgd_iter: 4
num_workers: 8
num_envs_per_worker: 8
lr: 5.0e-3
gamma: 0.99
batch_mode: complete_episodes
num_gpus: 1
num_cpus_per_worker: 1
model:
    custom_model: cc_model
    post_fcnet_hiddens: [128,128]
    post_fcnet_activation: relu
    conv_filters: [[16, [5, 5], 2], [32, [5, 5], 2], [64, [3, 3], 2]]
    conv_activation: relu
    vf_share_layers: False
env_config:
    world_shape: [24, 24]
    state_size: 48
    FOV: [5, 5]
    termination_no_new_coverage: 10
    max_episode_len: -1
    map_mode: random
    n_agents: 3
    merge: True
    revisit_penalty: False
    map_known: True

